apiVersion: v1
kind: Namespace
metadata:
  name: faas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cppserver-deployment
  namespace: faas
  labels:
    app: cppserver
spec:
  # replicas: 1 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: cppserver
  template:
    metadata:
      labels:
        app: cppserver
    spec:
      containers:
      - name: cppserver
        image: anishellore5/cppserver:latest
        imagePullPolicy: IfNotPresent
        resources:
          # limits:
          #   cpu: "1"
          # requests:
          #   cpu: "1"
        ports:
        - containerPort: 7000

---
apiVersion: v1
kind: Service
metadata:
  namespace: faas
  name: cppserver-service
spec:
  selector:
    app: cppserver
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  type: NodePort

